# Usar una imagen base de OpenJDK
FROM openjdk:11-jre-slim

# Añadir un volumen para la aplicación
VOLUME /tmp

# Copiar el archivo JAR al contenedor
COPY target/clubdeportivo-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto que el microservicio utiliza
EXPOSE 8081

# Ejecutar la aplicación
ENTRYPOINT ["java","-jar","/app.jar"]
